### ISSUE TITLE
npm install fails: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hellokatili** [hyperform/hyperform#63]
- Windows 10
- Node v6.10.0
- npm  v5.3.0

```
8401 verbose stack TypeError: Cannot read property '0' of undefined
8401 verbose stack     at rmStuff (C:\Program Files\nodejs\node_modules\npm\lib\unbuild.js:61:24)
8401 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
8401 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
8401 verbose stack     at lifecycle.then.then (C:\Program Files\nodejs\node_modules\npm\lib\install\action\unbuild.js:12:12)
8401 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
8401 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
8401 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
8401 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
8401 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
8401 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
8401 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
8401 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
8401 verbose stack     at runCallback (timers.js:651:20)
8401 verbose stack     at tryOnImmediate (timers.js:624:5)
8401 verbose stack     at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by hellokatili** [comment]
Don't know what the problem was.

I removed `node_modules` und ran `npm clear cache --force` and now it works...

¯\\_(ツ)_/¯

**Comment by Boldewyn** [comment]
No problem! I had similar issues myself before. Thanks for the notice!

**Comment by lyricat** [comment]
btw, it's `npm cache clear`
